package com.bxl.dao;

import com.bxl.entity.TestGoods;

public interface TestGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    int insert(TestGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    int insertSelective(TestGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    TestGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestGoods record);
}